// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPn_I5LRUNSlxrxrpqs35SfQKOUuZeJHA',
    appId: '1:270598531016:web:40a6357ba5dc571c4e42fd',
    messagingSenderId: '270598531016',
    projectId: 'lab11-aa6ab',
    authDomain: 'lab11-aa6ab.firebaseapp.com',
    storageBucket: 'lab11-aa6ab.firebasestorage.app',
    measurementId: 'G-J1Q0KSRB60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK5wKRNRgR49yya3GnpA00r5DNCKlUDxM',
    appId: '1:270598531016:android:193e29aee206b0db4e42fd',
    messagingSenderId: '270598531016',
    projectId: 'lab11-aa6ab',
    storageBucket: 'lab11-aa6ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYf2hBZzg5TVOXxe2Y2Vxn7yg6LLe1IRM',
    appId: '1:270598531016:ios:ed4e77da1756d8174e42fd',
    messagingSenderId: '270598531016',
    projectId: 'lab11-aa6ab',
    storageBucket: 'lab11-aa6ab.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYf2hBZzg5TVOXxe2Y2Vxn7yg6LLe1IRM',
    appId: '1:270598531016:ios:ed4e77da1756d8174e42fd',
    messagingSenderId: '270598531016',
    projectId: 'lab11-aa6ab',
    storageBucket: 'lab11-aa6ab.firebasestorage.app',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPn_I5LRUNSlxrxrpqs35SfQKOUuZeJHA',
    appId: '1:270598531016:web:f2ea2b22564d14c04e42fd',
    messagingSenderId: '270598531016',
    projectId: 'lab11-aa6ab',
    authDomain: 'lab11-aa6ab.firebaseapp.com',
    storageBucket: 'lab11-aa6ab.firebasestorage.app',
    measurementId: 'G-BDPM27LEYL',
  );
}
