// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-rDJnivdaGFfT8faEIfxieJ5zxYDFxE',
    appId: '1:1074746548698:web:e28b02fb19ff8dfcbe60e3',
    messagingSenderId: '1074746548698',
    projectId: 'mp-lab12-520d7',
    authDomain: 'mp-lab12-520d7.firebaseapp.com',
    storageBucket: 'mp-lab12-520d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx35peRXnUjbyKAXMbw1SrRqaGBzId-hs',
    appId: '1:1074746548698:android:a6fa4295ca245230be60e3',
    messagingSenderId: '1074746548698',
    projectId: 'mp-lab12-520d7',
    storageBucket: 'mp-lab12-520d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkBYgP9L5fp1vncuKQcfTc_Ih-Tjtl0CQ',
    appId: '1:1074746548698:ios:c4cce82519c2eae9be60e3',
    messagingSenderId: '1074746548698',
    projectId: 'mp-lab12-520d7',
    storageBucket: 'mp-lab12-520d7.firebasestorage.app',
    iosBundleId: 'com.example.firstFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkBYgP9L5fp1vncuKQcfTc_Ih-Tjtl0CQ',
    appId: '1:1074746548698:ios:c4cce82519c2eae9be60e3',
    messagingSenderId: '1074746548698',
    projectId: 'mp-lab12-520d7',
    storageBucket: 'mp-lab12-520d7.firebasestorage.app',
    iosBundleId: 'com.example.firstFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-rDJnivdaGFfT8faEIfxieJ5zxYDFxE',
    appId: '1:1074746548698:web:6b9dcae012bfb1c4be60e3',
    messagingSenderId: '1074746548698',
    projectId: 'mp-lab12-520d7',
    authDomain: 'mp-lab12-520d7.firebaseapp.com',
    storageBucket: 'mp-lab12-520d7.firebasestorage.app',
  );
}
